### ISSUE TITLE
Replace webpack bundling by rollupjs

### ISSUE THREAD

**Issue by henlz** [CraveFood/farmblocks#34]
Since we're removing sass from the project, we could remove our webpack config by [rollupjs](https://rollupjs.org/)

**Comment by fczuardi** [comment]
Webpack got replaced by babel on the monorepo.

The packages: alert, button and tooltip on the monorepo branch are using babel to generate the npm distribution.

For now it suffices because those components dont have dependencies (only react and styled-components as peer dependencies), and are meant to be integrated on a node project before bundling, so no need for bundling or tree shaking so far.

We can discuss however if it would be useful to include the non-transpiled source of our components on their npm packages with the es5 compatible lib, to facilitate the rollup integration by the projects using farmblocks. But that might be a different issue.

**Comment by fczuardi** [comment]
also maybe related with this discussion is that we are publishing the components with proptypes runtime checks (both before and after #57), and some people might not want it, they might want to strip them out for production builds. So including the non-transpiled sources can be useful on that case as well, then the consumer of our libs can customize the babel presets and  plugins for their preferences...
