### ISSUE TITLE
Publish master release when a PR is merged

### ISSUE THREAD

**Issue by seocam** [CraveFood/farmblocks#398]
When a PR is merged we have webhooks that creates a release called `master` in draft state. What we are currently missing it's a way to rename that release so something else and then publish it.

This is important so the farmblocks repo will fall into same category that our other repos allowing we to extract stats from that.

**Comment by fczuardi** [comment]
we also need to standardize the PRs texts, using a template, because some closed issues are not recognized due to be outside of the pattern expected by the webhook

**Comment by fczuardi** [comment]
opened https://github.com/CraveFood/farmblocks/issues/400

**Comment by fczuardi** [comment]
This issue is about generating github releases, or adapting our current workflow to finish the work started by the webhook described above, which means automatically renaming the master github release to something else (like the date) and change the status from draft to published.

Ideally we would be able to simply extend our travis rules for when a branch lands on master, to include the steps necessary for editing that master release created by the webhook. But since our travis rules runs at the same trigger as the webhook (pr merge), finding a way to make travis run *after* the webhook could be challenging.

Lerna and semantic release already organizes our releases with tags, and there are tools for creating github releases based on that model, such as https://github.com/conventional-changelog/releaser-tools/tree/master/packages/conventional-github-releaser but opting to go on that path would mean having to disable the auto "draft named master" release creation and let the creation/publish of the release be a single step performed after tests pass. So lets try to adapting the farmblocks model to fit in the existing api and webapp  model(multi environments, with qa) first, before going with the farmblocks-is-a-different-beast model.

**Comment by fczuardi** [comment]
The relevant GH API v3 (REST) doc page for release-related stuff is https://developer.github.com/v3/repos/releases/
