### ISSUE TITLE
[Alert] Use button component for dismiss button

### ISSUE THREAD

**Issue by fczuardi** [CraveFood/farmblocks#56]
Currently we use a styled button for the dismiss button.

We should use the farmblock button instead, to have consistency.

Also remove the "X" character by a proper icon font for the action.

**Comment by fczuardi** [comment]
@vitorpinho376 , consulting the latest specs, I don't think we have a button that fits the requirements for the default dismiss button on alerts, the Off Neutral types of Buttons and Triggers would mean a blue color on hover, and that don't look right on top of red, yellow or green...

![screen shot 2017-10-23 at 6 00 23 pm](https://user-images.githubusercontent.com/7760/31910531-8dc6fd90-b81c-11e7-82e5-9c05a7b6e574.png)
![screen shot 2017-10-23 at 6 00 13 pm](https://user-images.githubusercontent.com/7760/31910532-8e110188-b81c-11e7-94a9-85914fcc8131.png)

How should the hover and active states of the close button look like?

**Comment by vitorpinho376** [comment]
The real reason is that neutral buttons wouldn't be neutral when put above a darker background.
Btw, we won't have any case of placing a button above a yellow or red background. Blue is a maybe, but neutral buttons already fits on this case.

Component usage example:

![data filter results](https://user-images.githubusercontent.com/16965312/31910964-f119214c-b81d-11e7-99bd-8a367ec16fc9.png)

![data filter results hovered](https://user-images.githubusercontent.com/16965312/31910963-f0eaf902-b81d-11e7-9cc6-68aacc33e479.png)

**Comment by vitorpinho376** [comment]
Just crossed my mind we are using it inside the alerts for closing it...
I think this will be the less clicked button on the interface, can't see a problem right now. Any suggestions?

**Comment by fczuardi** [comment]
> Just crossed my mind we are using it inside the alerts for closing it...

LOL, sorry if the issue title, description and labels didn't made it clear that this was about the alert comopnent :)
